### ISSUE TITLE
Help tweak this to use hotkey instead of mouse button

### ISSUE THREAD

**Issue by NeighNeighNeigh** [timginter/hammerspoon-mouse-wheel-autoscroll#1]
Hi Tim,

Thank you for this incredible Hammerspoon script, it seems super handy! I would love to trigger this with a keyboard key instead of the mouse key. I examined the code, hoping something would jump out at me, but it was honestly too complex for my current understanding. I'm am very new to Hammerspoon and have no real programming background, so please forgive my naivety… I'm just wondering if it would be much trouble to include a keyboard triggered version?

Cheers, Nathan

**Comment by timginter** [comment]
hi Nathan,

it would need rewriting the scroll logic, unfortunately. script uses the "drag" event on mouse wheel for scrolling. key presses do not have the same "drag" event so you'd have to hook up to mouse movement and check if your trigger key is pressed at the same time as the mouse being moved.

it might be easier to use another snippet to remap your keyboard key to mouse wheel button as a workaround

TIM

**Comment by NeighNeighNeigh** [comment]
No worries Tim, thanks for taking the time to get back to me- your suggested workaround is working well.
