### ISSUE TITLE
mouse-wheel button has to be pressed

### ISSUE THREAD

**Issue by ghost** [timginter/hammerspoon-mouse-wheel-autoscroll#3]
Hi,

My question is:  Is there any way to edit the script so I don't have to press the scroll wheel all the time? My idea is that it works like in firefox. You press the mouse wheel once and you can scroll as long you don't press the mouse wheel or mouse button1. I don't really know how to implement that. Can you help me with that?

With kind regards  Mario

**Comment by timginter** [comment]
hi @teamvegan , late reply - holiday season. I don't have the old code anymore, but I had an early version written like that and, for me, it worked much worse than the current implementation.

I am not planning to implement it and maintain 2 version, but you can implement it with a fairly simple boolean toggle, e.g. toggleButtonPressed. When releasing the mouse button (overrideScrollMouseUp override), check for the boolean:
- if not true - set it to true and run the code that's now in overrideScrollMouseDown
- if true - set it to false and run the code that's now in overrideScrollMouseUp
