### ISSUE TITLE
how to exclude to run from certain application?

### ISSUE THREAD

**Issue by omshejul** [timginter/hammerspoon-mouse-wheel-autoscroll#4]

**Comment by timginter** [comment]
easiest would probably be by window title. Check needs to be inside the conditions for Middle Mouse Button for key pressed and release - lines 31 and 38.

Right inside those "ifs", get the top-most window's title. If the title matches any of the ones you want to exclude, return "false" - it will send the original Middle Mouse Button event and not do any of the scrolling logic
